### ISSUE TITLE
Re-exporting assert2 macros

### ISSUE THREAD

**Issue by tinkerware** [de-vri-es/assert2-rs#15]
Is it possible to re-export the macros in this crate without problems? A naive `pub use assert2::assert as verify` in crate A followed by `use A::*; verify!(2 + 2 == 4);` in crate B fails with a `failed to resolve: could not find 'assert2' in '{{root}}'` error for me when I run `cargo test`. 

I'm not that familiar with macros in Rust, so this is likely due to me not correctly re-exporting macros properly (looks like there is a lot of history on this front in Rust). I did look at `assert2::assert`, and I notice that the reference to `::assert2::check_impl` does not use `$crate` or the `macro_export` attribute `local_inner_macros`, which I thought was the current way to preserve macro hygiene during expansion. What am I missing?

**Comment by de-vri-es** [comment]
`$crate` or `local_inner_macros` won't directly help, since the proc macros are in a different crate than the runtime helpers. They have to be, since proc macro crates can't export normal functions or structs.

I'm open to ideas though. It would be nice to support directly re-exporing the macros.

**Comment by m-ou-se** [comment]
Looks like passing `$crate` as an argument to the proc macros works. See #16.

**Comment by de-vri-es** [comment]
Fixed by #16, and released as 0.3.1 :)

**Comment by de-vri-es** [comment]
Fixed by #16 and released as 0.3.1.

Thanks for reporting the issue :)
