### ISSUE TITLE
let_check macro

### ISSUE THREAD

**Issue by StragaSevera** [de-vri-es/assert2-rs#18]
I think it would be useful to have a `let_check` macro, which behaves like `let_assert` macro, but with `check` semantics.

**Comment by m-ou-se** [comment]
That's not possible, because the code continues after a failed `check`, and then there's no value to assign in the `let`.

```rust
let_check!(Some(x) = "abc".find('x'));
println!("{}" , x); // What is `x` here?
```

**Comment by StragaSevera** [comment]
Got it, thanks!
