### ISSUE TITLE
Support for asserting `Result`

### ISSUE THREAD

**Issue by bluecube** [de-vri-es/assert2-rs#24]
It would be nice to allow writing `assert!(value_of_type_result)` which would be functionally equivalent to `assert!(value_of_type_result.is_ok())`, but with nicer messages (containing Err value formated by Debug).

**Comment by de-vri-es** [comment]
Hey! Thanks for the suggestion.

This is already supported. However, you have to write:

```rust
assert!(let Ok(_) = some_result());
```

It does require that the `Ok` value is also `Debug`. When we get specialization in user code, we can improve on that :)

**Comment by m-ou-se** [comment]
Note that you can also just write `value_of_type_result.unwrap();`. This also includes the `Debug` formatted `Err` value in the panic message.

**Comment by bluecube** [comment]
Thank you both for the answers. What I need is probably just unwrap, and I somehow managed to miss that :)

**Comment by de-vri-es** [comment]
Although `unwrap()` does give less nice messages (with less formatting and less colors, mainly).

And if you want to perform more checks on the Ok value, you can do:
```rust
let_assert!(Ok(foo) = do_thing());
assert!(foo.thing == 5);
```
