### ISSUE TITLE
Coloring message

### ISSUE THREAD

**Issue by shafouz** [de-vri-es/assert2-rs#26]
Hi, is there any builtin way to color the assert message:

![WindowsTerminal_UK9PC32jTi](https://user-images.githubusercontent.com/38974831/198837833-42996c2a-a8fc-415a-a201-3fbc161e27d0.png)

Any way to make the ```newlines are not allowed``` colored?

**Comment by de-vri-es** [comment]
I assume you went for coloring it with an existing terminal colors library?

**Comment by de-vri-es** [comment]
Fair enough. I could make it bold by default I suppose. We do want to draw attention to the custom message.

**Comment by shafouz** [comment]
That sounds good
