### ISSUE TITLE
Conflict with --nocapture option

### ISSUE THREAD

**Issue by TheFurnace** [de-vri-es/assert2-rs#27]
### Issue
When running `cargo test` with the `--nocapture` option e.g. `cargo test --package foo -- --nocapture` the output from failed assert2 assertions conflicts with the output from `--nocapture`

#### Without  `--nocapture`
![image](https://user-images.githubusercontent.com/18475630/212807318-d3041729-26cd-4036-b89a-803fff22b0da.png)
#### With `--nocapture`
![image](https://user-images.githubusercontent.com/18475630/212807399-ccf39421-a7d3-4a23-8390-d4d5e67ad59d.png)

### Comment
It is somewhat expected that test output with `--nocapture` is messy, but I've never seen it go this wild. Thought I would drop an issue so that anyone who searches this in the future can hopefully save some time figuring it out.

Also, the crate is a huge upgrade from standard assert macros! great work!

**Comment by m-ou-se** [comment]
That's probably happening because assert2 uses many `eprint`s to write its output, instead of just one single write to stderr.

I'm not sure if this is worth fixing, but buffering the entire message and then printing it with a single `write()` would improve this.

**Comment by de-vri-es** [comment]
Fixed by @TheFurnace in #28, and released as `v0.3.8` :tada:
