### ISSUE TITLE
check!() and/or assert!() outside of #[test]s

### ISSUE THREAD

**Issue by m-ou-se** [de-vri-es/assert2-rs#7]
The documentation mentions that `check!()` might not panic in the future, if there is a way to fail a `#[test]` without a panic. Does that mean that `check!()` should never be used outside of `#[test]`s? How about `assert!()`?

**Comment by de-vri-es** [comment]
`check` and `assert` are certainly meant to be usable outside tests. It depends of course on the test framework what we can do. Maybe `check` will still panic outside of tests, maybe it will only print things outside of tests.

I think the only guarantee we can give that will never change is that `check` will *not* panic if the check doesn't fail, and it will print a failure message if the check did fail.

**Comment by de-vri-es** [comment]
I added a sentence to the documentation stating that the macros are usable outside of test cases: b8902521278ea4a5ceaf9e028081cfd9f8315226. You think that's enough?

**Comment by m-ou-se** [comment]
New docs look great. :)
